## Danish company data

In [3]:
#imports
import pandas as pd
import numpy as np
pd.set_option('display.max_colwidth', 500)
import math
#import for requests
import requests

#import beautiful soup
from bs4 import BeautifulSoup

#we will use selenium webdriver
from selenium import webdriver
from time import sleep
from selenium.webdriver.common.by import By
import os

In [5]:
#create webdriver instance
driver = webdriver.Chrome()

#get the url with login page
driver.get("https://www.proff.dk/segmentering?ef=2&et=52487&c=Aktieselskab&c=Anpartsselskab&c=Iv%C3%A6rks%C3%A6tterselskab&c=Forening%20eller%20selskab%20med%20begr%C3%A6nset%20ansvar&c=Kommanditaktieselskab%2FPartnerselskab&c=Kommanditselskab&c=Medarbejderinvesteringsselskab&c=Personligt%20ejet%20Mindre%20Virksomhed&c=Selskab%20med%20begr%C3%A6nset%20ansvar&samplerFilter=true")

sleep(1)
try:
    driver.find_element("xpath","/html/body/div[1]/div/div/div/div[2]/div/button[3]").click()
except:
    pass

links = []
soup = BeautifulSoup(driver.page_source, "html5")

for link in soup.find_all("div", class_="listing"):
    links.append(link.a['href'])

In [6]:
links

['/firma/salling-group-as/brabrand/-/35954716/',
 '/firma/novo-nordisk-as/bagsv%C3%A6rd/-/24256790/',
 '/firma/coop-danmark-as/albertslund/-/26259495/',
 '/firma/forbruger-kontakt-as/taastrup/-/26899737/',
 '/firma/danske-bank-as/k%C3%B8benhavn-k/-/61126228/',
 '/firma/fakta-as/albertslund/-/11517498/',
 '/firma/post-danmark-as/k%C3%B8benhavn-s/-/26663903/',
 '/firma/danish-crown-as/randers-s%C3%B8/-/26121264/',
 '/firma/jks-as/ringk%C3%B8bing/-/19687236/',
 '/firma/moment-as/k%C3%B8benhavn-v/-/25328949/',
 '/firma/iss-facility-services-as/s%C3%B8borg/-/14406042/',
 '/firma/falck-danmark-as/k%C3%B8benhavn-sv/-/16271241/',
 '/firma/siemens-gamesa-renewable-energy-as/brande/-/76486212/',
 '/firma/lego-system-as/billund/-/47458714/',
 '/firma/lidl-danmark-ks/kolding/-/26630797/',
 '/firma/duos-as/k%C3%B8benhavn-sv/-/25477154/',
 '/firma/carelink-as/randers-sv/-/30568176/',
 '/firma/coor-service-management-as/herlev/-/10683548/',
 '/firma/tryg-forsikring-as/ballerup/-/24260666/',
 '/firma/h-m-hennes-mauritz-as/k%C3%B8benhavn-k/-/33345828/',
 '/firma/nuuday-as/k%C3%B8benhavn-sv/-/40075291/',
 '/firma/jyske-bank-as/silkeborg/-/17616617/',
 '/firma/nykredit-realkredit-as/k%C3%B8benhavn-v/-/12719280/',
 '/firma/ikea-as/taastrup/-/50574911/',
 '/firma/aldi-danmark-aps/albertslund/-/89797217/']

In [42]:
links[0] = links[0].replace("firma", "regnskab")
url = requests.get("https://www.proff.dk"+links[0])
soup = BeautifulSoup(url.content, "html5")
table = soup.find_all('table')
df = pd.read_html(str(table))

In [43]:
df_final = pd.concat([pd.read_html(str(table))[1].transpose(), pd.read_html(str(table))[2].transpose()], axis=1)

In [44]:
df_final

,0,1,2,3,4,5,6,7,8,9,...,34,35,36,37,38,39,40,41,42,43
RESULTATREGNSKAB i hele 1000,Valutakode,Nettoomsætning,Vareforbrug,Øvrige omkostninger,Bruttofortjeneste,Personaleomkostninger,Afskrivninger,Kapacitetsomkostninger,Primært resultat,Finansielle indtægter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12,DKK,241.000,32.603.000,-,14.641.000,-6.705.000,-2.067.000,0,2.176.000,108.000,...,0,11.929.000,0,5.000,0,19.000,10.202.000,2.283.000,16.016.000,37.392.000
2020-12,DKK,45.684.000,32.099.000,-,13.585.000,-6.342.000,-1.969.000,-3.342.000,1.932.000,52.000,...,0,13.078.000,0,5.000,0,0,9.667.000,5.587.000,15.265.000,35.953.000
2019-12,DKK,42.701.000,29.722.000,-,12.979.000,-6.023.000,-1.934.000,-3.492.000,1.530.000,62.000,...,0,13.607.000,0,4.000,0,0,9.432.000,6.721.000,16.167.000,35.964.000
2018-12,DKK,41.969.000,29.539.000,-,12.430.000,-5.737.000,659.000,-5.029.000,1.005.000,84.000,...,0,1.853.000,0,37.000,4.000,24.000,9.495.000,7.540.000,17.072.000,23.194.000
2017-12,DKK,40.406.000,-,-,11.741.000,-5.334.000,-830.000,11.275.000,466.000,1.481.000,...,-,1.944.000,-,-,-,-,8.738.000,1.831.000,16.643.000,22.244.000
2016-12,DKK,39.837.000,-,-,11.170.000,-5.239.000,-438.000,10.427.000,743.000,910.000,...,-,2.036.000,-,-,-,-,6.759.000,1.751.000,17.477.000,26.863.000
2015-12,DKK,39.079.000,-,-,11.105.000,-5.161.000,-367.000,10.208.000,897.000,1.284.000,...,-,2.189.000,8.092.000,-,-,-,5.511.000,1.666.000,15.399.000,26.691.000
2014-12,DKK,39.027.000,-,-,6.521.000,-5.137.000,-397.000,5.534.000,987.000,1.148.000,...,-,247.000,7.218.000,-,-,-,4.615.000,1.680.000,13.525.000,20.718.000
2013-12,DKK,39.135.000,-,-,6.298.000,-4.973.000,-333.000,5.306.000,992.000,1.085.000,...,-,-,250.000,-,-,-,3.651.000,1.633.000,5.725.000,28.828.000
Unnamed: 10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BALANCEREGNSKAB i hele 1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Ansvarlig lånekapital (Samlepost),Langfristet gæld i alt,Kortfristet gæld til nærtstående parter,Kortfristet gæld til realkreditinstitutter,Kortfristet gæld til banker,Selskabsskat,Varekreditorer,Anden gæld,Kortfristet gæld i alt,Passiver i alt

In [48]:
#set index to the first columns and transpose
df1 = pd.read_html(str(table))[1].set_index("RESULTATREGNSKAB  i hele 1000").transpose()

In [49]:
#set index to the first columns and transpose
df2 = pd.read_html(str(table))[2].set_index("BALANCEREGNSKAB  i hele 1000").transpose()

In [51]:
#merge the two dataframes columnwise
df = pd.concat([df1,df2], axis=1)

In [52]:
#print the datframe
df

,Valutakode,Nettoomsætning,Vareforbrug,Øvrige omkostninger,Bruttofortjeneste,Personaleomkostninger,Afskrivninger,Kapacitetsomkostninger,Primært resultat,Finansielle indtægter,...,Ansvarlig lånekapital (Samlepost),Langfristet gæld i alt,Kortfristet gæld til nærtstående parter,Kortfristet gæld til realkreditinstitutter,Kortfristet gæld til banker,Selskabsskat,Varekreditorer,Anden gæld,Kortfristet gæld i alt,Passiver i alt
2021-12,DKK,241.000,32.603.000,-,14.641.000,-6.705.000,-2.067.000,0,2.176.000,108.000,...,0,11.929.000,0,5.000,0,19.000,10.202.000,2.283.000,16.016.000,37.392.000
2020-12,DKK,45.684.000,32.099.000,-,13.585.000,-6.342.000,-1.969.000,-3.342.000,1.932.000,52.000,...,0,13.078.000,0,5.000,0,0,9.667.000,5.587.000,15.265.000,35.953.000
2019-12,DKK,42.701.000,29.722.000,-,12.979.000,-6.023.000,-1.934.000,-3.492.000,1.530.000,62.000,...,0,13.607.000,0,4.000,0,0,9.432.000,6.721.000,16.167.000,35.964.000
2018-12,DKK,41.969.000,29.539.000,-,12.430.000,-5.737.000,659.000,-5.029.000,1.005.000,84.000,...,0,1.853.000,0,37.000,4.000,24.000,9.495.000,7.540.000,17.072.000,23.194.000
2017-12,DKK,40.406.000,-,-,11.741.000,-5.334.000,-830.000,11.275.000,466.000,1.481.000,...,-,1.944.000,-,-,-,-,8.738.000,1.831.000,16.643.000,22.244.000
2016-12,DKK,39.837.000,-,-,11.170.000,-5.239.000,-438.000,10.427.000,743.000,910.000,...,-,2.036.000,-,-,-,-,6.759.000,1.751.000,17.477.000,26.863.000
2015-12,DKK,39.079.000,-,-,11.105.000,-5.161.000,-367.000,10.208.000,897.000,1.284.000,...,-,2.189.000,8.092.000,-,-,-,5.511.000,1.666.000,15.399.000,26.691.000
2014-12,DKK,39.027.000,-,-,6.521.000,-5.137.000,-397.000,5.534.000,987.000,1.148.000,...,-,247.000,7.218.000,-,-,-,4.615.000,1.680.000,13.525.000,20.718.000
2013-12,DKK,39.135.000,-,-,6.298.000,-4.973.000,-333.000,5.306.000,992.000,1.085.000,...,-,-,250.000,-,-,-,3.651.000,1.633.000,5.725.000,28.828.000
Unnamed: 10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
#export to excel

cwd = os.getcwd()

df.to_excel(cwd + "/DanishCompanydata.xlsx")